version: '3.3'

networks:
  crud:
    driver: 'bridge'

volumes:
  database:
    driver: 'local'

services:
  backend:
    container_name: crud-backend
    restart: always
    build:
      context: ./
      args:
        APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/current
    links:
      - database
    networks:
      - crud
    depends_on:
      - database
  
  database:
    container_name: crud-database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    environment:
      - MYSQL_DATABASE=crud
      - MYSQL_USER=crud
      - MYSQL_PASSWORD=crud
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - crud